// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYgSVIB19TuyKVTPGnbt8RRNgZEMnsITM',
    appId: '1:325126223708:web:290d392ff2c6cd9b74f399',
    messagingSenderId: '325126223708',
    projectId: 'capstone-458510',
    authDomain: 'capstone-458510.firebaseapp.com',
    storageBucket: 'capstone-458510.firebasestorage.app',
    measurementId: 'G-VGGPQNEKJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHZ4lxCsMJtQ2SyKzuEja9-XuAzIPTUvQ',
    appId: '1:325126223708:android:fe41f0a3225f710d74f399',
    messagingSenderId: '325126223708',
    projectId: 'capstone-458510',
    storageBucket: 'capstone-458510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjxKmTlLm5LZFLo-FoOilMqinwYfu9Pg',
    appId: '1:325126223708:ios:aa6c2ea31249a5e074f399',
    messagingSenderId: '325126223708',
    projectId: 'capstone-458510',
    storageBucket: 'capstone-458510.firebasestorage.app',
    iosBundleId: 'com.example.oneCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTjxKmTlLm5LZFLo-FoOilMqinwYfu9Pg',
    appId: '1:325126223708:ios:aa6c2ea31249a5e074f399',
    messagingSenderId: '325126223708',
    projectId: 'capstone-458510',
    storageBucket: 'capstone-458510.firebasestorage.app',
    iosBundleId: 'com.example.oneCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYgSVIB19TuyKVTPGnbt8RRNgZEMnsITM',
    appId: '1:325126223708:web:945171622067e5cf74f399',
    messagingSenderId: '325126223708',
    projectId: 'capstone-458510',
    authDomain: 'capstone-458510.firebaseapp.com',
    storageBucket: 'capstone-458510.firebasestorage.app',
    measurementId: 'G-FT6CKCWVXK',
  );

}